// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qcfyyjwcxutxbljhgsbi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjZnl5andjeHV0eGJsamhnc2JpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MjM1MTIsImV4cCI6MjA2ODk5OTUxMn0.LX3rKUgSsw46cy3VTCJmYLlZBOV_caHc8x6qRe5xu7Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});